name: Update Stock Web

on:
  schedule:
    - cron: '0 8 * * 1-5' # 每周一至五，UTC 08:00 (台北時間 16:00) 自動跑
  workflow_dispatch: # 允許你手動點擊按鈕執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install yfinance pandas numpy

      - name: Run script
        run: python app.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages # 會將生成的 index.html 發布到這個分支
